import 'package:flutter/material.dart';
import 'models.dart';

// ─── All 10 StudyNest themes ──────────────────────────────────────────────────

const List<AppThemeDef> appThemes = [
  AppThemeDef(
    id: 'clair', label: 'Clair', emoji: '☀️',
    bg:        Color(0xFFFBF6F1),
    surface:   Color(0xFFFFFFFF),
    surface2:  Color(0xFFF2EBE4),
    accent:    Color(0xFF7C2333),
    accent2:   Color(0xFFB03D52),
    textColor: Color(0xFF1A0A0F),
    muted:     Color(0xFF8A7070),
    line:      Color(0xFFE8DDD6),
  ),
  AppThemeDef(
    id: 'sombre', label: 'Sombre', emoji: '🌙',
    bg:        Color(0xFF161119),
    surface:   Color(0xFF221B29),
    surface2:  Color(0xFF2E2538),
    accent:    Color(0xFFE2536E),
    accent2:   Color(0xFFFF7A91),
    textColor: Color(0xFFF5EEF3),
    muted:     Color(0xFF887890),
    line:      Color(0xFF3A2E44),
    isDark:    true,
  ),
  AppThemeDef(
    id: 'sakura', label: 'Sakura', emoji: '🌸',
    bg:        Color(0xFFFFF2F6),
    surface:   Color(0xFFFFFFFF),
    surface2:  Color(0xFFFFE5EE),
    accent:    Color(0xFFE8637F),
    accent2:   Color(0xFFFF8FA3),
    textColor: Color(0xFF2A1018),
    muted:     Color(0xFF9A6070),
    line:      Color(0xFFFFCDD8),
  ),
  AppThemeDef(
    id: 'ocean', label: 'Océan', emoji: '🌊',
    bg:        Color(0xFFEAF6F8),
    surface:   Color(0xFFFFFFFF),
    surface2:  Color(0xFFD5EFF3),
    accent:    Color(0xFF1C8CA3),
    accent2:   Color(0xFF3AADBE),
    textColor: Color(0xFF082028),
    muted:     Color(0xFF5A8590),
    line:      Color(0xFFC0DFE5),
  ),
  AppThemeDef(
    id: 'galaxie', label: 'Galaxie', emoji: '🔭',
    bg:        Color(0xFF130E29),
    surface:   Color(0xFF1E1838),
    surface2:  Color(0xFF2A2248),
    accent:    Color(0xFF8B6CF0),
    accent2:   Color(0xFFAA90FF),
    textColor: Color(0xFFF0EAFF),
    muted:     Color(0xFF7868A8),
    line:      Color(0xFF342A58),
    isDark:    true,
  ),
  AppThemeDef(
    id: 'bibliotheque', label: 'Bibliothèque', emoji: '📚',
    bg:        Color(0xFFF5EEDC),
    surface:   Color(0xFFFFFBF0),
    surface2:  Color(0xFFEDE0C4),
    accent:    Color(0xFF8A5A2B),
    accent2:   Color(0xFFAD7A45),
    textColor: Color(0xFF201408),
    muted:     Color(0xFF886050),
    line:      Color(0xFFDDD0B0),
  ),
  AppThemeDef(
    id: 'foret', label: 'Forêt', emoji: '🌿',
    bg:        Color(0xFFEEF5E9),
    surface:   Color(0xFFFFFFFF),
    surface2:  Color(0xFFD8EDD0),
    accent:    Color(0xFF4C7A3B),
    accent2:   Color(0xFF6A9E58),
    textColor: Color(0xFF0E1E0A),
    muted:     Color(0xFF5A7850),
    line:      Color(0xFFC4DDB8),
  ),
  AppThemeDef(
    id: 'science', label: 'Science', emoji: '🔬',
    bg:        Color(0xFFEFF7F6),
    surface:   Color(0xFFFFFFFF),
    surface2:  Color(0xFFCFEBE8),
    accent:    Color(0xFF1F8A94),
    accent2:   Color(0xFF3AABB5),
    textColor: Color(0xFF061A1C),
    muted:     Color(0xFF508088),
    line:      Color(0xFFB8D8D5),
  ),
  AppThemeDef(
    id: 'reseau', label: 'Réseau', emoji: '📡',
    bg:        Color(0xFFEAF1FB),
    surface:   Color(0xFFFFFFFF),
    surface2:  Color(0xFFD0E2F5),
    accent:    Color(0xFF1857A4),
    accent2:   Color(0xFF3878CC),
    textColor: Color(0xFF060E20),
    muted:     Color(0xFF506080),
    line:      Color(0xFFBDD0E8),
  ),
  AppThemeDef(
    id: 'construction', label: 'Construction', emoji: '🏗️',
    bg:        Color(0xFFFBF4E3),
    surface:   Color(0xFFFFFFFF),
    surface2:  Color(0xFFEEE0BE),
    accent:    Color(0xFFE0A106),
    accent2:   Color(0xFFFFBF2A),
    textColor: Color(0xFF201400),
    muted:     Color(0xFF907840),
    line:      Color(0xFFE0CFA0),
  ),
];

// ─── Flutter ThemeData builder ────────────────────────────────────────────────

ThemeData buildThemeData(AppThemeDef t) {
  final scheme = ColorScheme(
    brightness:           t.isDark ? Brightness.dark : Brightness.light,
    primary:              t.accent,
    onPrimary:            Colors.white,
    secondary:            t.accent2,
    onSecondary:          Colors.white,
    error:                const Color(0xFFD32F2F),
    onError:              Colors.white,
    surface:              t.surface,
    onSurface:            t.textColor,
    surfaceContainerHighest: t.surface2,
  );

  return ThemeData(
    useMaterial3:    true,
    colorScheme:     scheme,
    scaffoldBackgroundColor: t.bg,
    splashColor:     t.accent.withValues(alpha: 0.08),
    highlightColor:  t.accent.withValues(alpha: 0.04),
    appBarTheme: AppBarTheme(
      backgroundColor:    t.bg,
      surfaceTintColor:   Colors.transparent,
      elevation:          0,
      titleTextStyle: TextStyle(
        color:       t.textColor,
        fontSize:    20,
        fontWeight:  FontWeight.w800,
        fontFamily:  'Fraunces',
      ),
      iconTheme: IconThemeData(color: t.textColor),
    ),
    cardTheme: CardThemeData(
      color:        t.surface,
      surfaceTintColor: Colors.transparent,
      elevation:    0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(20),
        side: BorderSide(color: t.line),
      ),
    ),
    chipTheme: ChipThemeData(
      backgroundColor:    t.surface2,
      labelStyle: TextStyle(color: t.muted, fontWeight: FontWeight.w700, fontSize: 12.5),
      side:        BorderSide.none,
      shape:       const StadiumBorder(),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled:           true,
      fillColor:        t.bg,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide:   BorderSide(color: t.line),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide:   BorderSide(color: t.line),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide:   BorderSide(color: t.accent, width: 1.5),
      ),
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      hintStyle:  TextStyle(color: t.muted),
    ),
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      backgroundColor: t.accent,
      foregroundColor: Colors.white,
      elevation:       8,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(18)),
    ),
    bottomNavigationBarTheme: BottomNavigationBarThemeData(
      backgroundColor: t.surface,
      selectedItemColor:   t.accent,
      unselectedItemColor: t.muted,
      type: BottomNavigationBarType.fixed,
      elevation: 12,
    ),
  );
}
